### ISSUE TITLE
helm install question

### ISSUE THREAD

**Issue by imgolye** [gocrane/crane#194]
## Describe the feature
executive command   helm install crane -n crane-system --create-namespace crane/crane

cause as follow

Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "webhook-server-tls" in namespace "crane-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "crane"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "crane-system"

how to solve

**Comment by qmhu** [comment]
Hi imgolye:
Have you ever install crane before and you try to install again?
You can try to uninstall crane first to clean env then reinstall it.

`helm uninstall crane -n crane-system`
