### ISSUE TITLE
what's the difference between Crane and Kubecost？

### ISSUE THREAD

**Issue by tedgxt** [gocrane/crane#211]
## Describe the feature
Kubecost also provide the ability to collect in-cluster cost info. 
what's the difference between Crane and Kubecost ？

**Comment by qmhu** [comment]
Crane is a one-stop-shop project to help Kubernetes users to save cloud resource usage which including more than cost report, for example: tools for cost optimization and Pod QoS.
Welcome to join us and give more advise.
