### ISSUE TITLE
Support install crane-agent in Kind

### ISSUE THREAD

**Issue by qmhu** [gocrane/crane#232]
**Describe the bug**

<img width="1729" alt="wecom-temp-cbdaadbbc7e0969eff1fb91c934eec55" src="https://user-images.githubusercontent.com/6251116/160078347-4cf027b0-556c-48eb-a145-8e9cf1e79125.png">
install crane-agent in kind failed

**Reproduce steps**

**Expected behavior**

Crane might support install agent in kind cluster.

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0] 0.3.0

**Comment by lbbniu** [comment]
Modify the runtime-endpoint configuration, the k8s cri deployed by kind is containerd. As follows:
```
...
          command:
            - /crane-agent
            - -v=4
            - --runtime-endpoint=unix:///rootvar/run/containerd/containerd.sock
...
```
