### ISSUE TITLE
Crane Dashboard  Crane URL	Config

### ISSUE THREAD

**Issue by Ulicong** [gocrane/crane#237]
## Describe the feature
Crane Dashboard  Crane URL	Config  Address is?

**Comment by chenkaiyue** [comment]
You can use kubectl port-forward or nodeport to expose Service craned's dashboard-service port, and the Crane Dashboard Crane URL is just the url which you can access  Service craned's dashboard-service port.

**Comment by Ulicong** [comment]
thanks
