### ISSUE TITLE
Error: failed to download "crane/crane"

### ISSUE THREAD

**Issue by jiker-burce** [gocrane/crane#245]
**Describe the bug**
Just see the next steps

**Reproduce steps**
➜  ~ helm repo add crane https://gocrane.github.io/helm-charts

"crane" has been added to your repositories
➜  ~ helm install crane -n crane-system --create-namespace crane/crane

Error: failed to download "crane/crane" (hint: running `helm repo update` may help)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: v1.22.5
 - Crane Version: can't install
 - Browser: do not go to this step now

**Comment by jiker-burce** [comment]
It's ok now, just need to try a few more times for `helm install crane -n crane-system --create-namespace crane/crane`

**Comment by jiker-burce** [comment]
we'll find the crane deployment can't be ready for a long time, we could check it by the follow steps:
```
➜  ~ kubectl get deploy -n crane-system      
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
craned                          0/1     1            0           31m
fadvisor                        1/1     1            1           27m
grafana                         1/1     1            1           55m
metric-adapter                  1/1     1            1           31m
prometheus-kube-state-metrics   1/1     1            1           85m
prometheus-server               1/1     1            1           85m

➜  ~ k get rs -n crane-system          
NAME                                      DESIRED   CURRENT   READY   AGE
craned-66dd6fcc77                         1         1         0       31m
fadvisor-7df4f877d9                       1         1         1       28m
grafana-6bfdb887b4                        1         1         1       55m
metric-adapter-7ff58484b5                 1         1         1       31m
prometheus-kube-state-metrics-67ff4c6d5   1         1         1       85m
prometheus-server-68994c6b54              1         1         1       85m

➜  ~ k describe replicaset craned-66dd6fcc77 -n crane-system
Replicas:       1 current / 1 desired
Pods Status:    0 Running / 1 Waiting / 0 Succeeded / 0 Failed

// check: all related images are downloaded
// check events: Failed to pull image "docker.io/gocrane/dashboard:v0.3.0": rpc error: code = Unknown desc = context canceled
// at last, I try to rescpe the number of replicsets to 2, let the k8s try to do sth for this condition.
// Fine, it works now.
```
- My[ ](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application/#my-pod-stays-waiting)pod stays waiting 
If a Pod is stuck in the Waiting state, then it has been scheduled to a worker node, but it can't run on that machine. Again, the information from kubectl describe ... should be informative. The most common cause of Waiting pods is a failure to pull the image. There are three things to check:
  - Make sure that you have the name of the image correct.
  - Have you pushed the image to the registry?
  - Try to manually pull the image to see if the image can be pulled. For example, if you use Docker on your PC, run docker pull <image>.

**Comment by qmhu** [comment]
If it works now, then can we close this issue ?

**Comment by jiker-burce** [comment]
@qmhu yes, thanks.
