### ISSUE TITLE
FailedOfferRecommend

### ISSUE THREAD

**Issue by no-frown** [gocrane/crane#250]
**Describe the bug**
1. I created analytics resource

```yaml
apiVersion: analysis.crane.io/v1alpha1
kind: Analytics
metadata:
  name: abc-hpa
  namespace: default
spec:
  type: HPA                        # This can only be "Resource" or "HPA".
  completionStrategy:
    completionStrategyType: Periodical  # This can only be "Once" or "Periodical".
    periodSeconds: 600                  # analytics selected resources every 10 minutes
  resourceSelectors:                    # defines all the resources to be select with
    - kind: Deployment
      apiVersion: apps/v1
      name: abc


```
2. I get recommendations got err
> kubectl get recommendations.analysis.crane.io abc-hpa-mtszn -n default -o yaml

```yaml
apiVersion: analysis.crane.io/v1alpha1
kind: Recommendation
metadata:
  creationTimestamp: "2022-04-07T10:19:17Z"
  generateName: abc-hpa-hpa-
  generation: 2
  labels:
    app: abc
    app.kubernetes.io/managed-by: nocalhost
    env: prod
    group: default
  name: abc-hpa-hpa-mtszn
  namespace: default
  ownerReferences:
  - apiVersion: analysis.crane.io/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: Analytics
    name: abc-hpa
    uid: b7fb74cb-da8f-49fa-bb6c-b4e698bd03ee
  resourceVersion: "773805144"
  selfLink: /apis/analysis.crane.io/v1alpha1/namespaces/default/recommendations/abc-hpa-hpa-mtszn
  uid: 3965b3a1-804d-4cd2-95c8-e39c5a17b05e
spec:
  adoptionType: StatusAndAnnotation
  completionStrategy:
    completionStrategyType: Periodical
    periodSeconds: 600
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: default
    namespace: default
  type: HPA
status:
  conditions:
  - lastTransitionTime: "2022-04-07T10:19:17Z"
    message: 'Failed to offer recommend, Recommendation default/abc-hpa-hpa-mtszn:
      EHPAAdvisor checkMinCpuUsageThreshold failed: strconv.ParseFloat: parsing "":
      invalid syntax'
    reason: FailedOfferRecommend
    status: "False"
    type: Ready
  lastUpdateTime: "2022-04-07T10:19:17Z"
```
Failed to offer recommend, Recommendation default/abc-hpa-hpa-mtszn:
      EHPAAdvisor checkMinCpuUsageThreshold failed: strconv.ParseFloat: parsing "":
      invalid syntax
**Reproduce steps**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.17]
 - Crane Version: [e.g. 0.3.0]

**Comment by qmhu** [comment]
It's a mistake in crane chart, I fixed by https://github.com/gocrane/helm-charts/pull/42

Would you please update chart and reinstall it?
'''
# update your crane version
helm repo update

# uninstall
helm uninstall crane -n crane-system

# install 
helm install crane -n crane-system --create-namespace crane/crane
'''

**Comment by chen-shiwei** [comment]
> It's a mistake in crane chart, I fixed by [gocrane/helm-charts#42](https://github.com/gocrane/helm-charts/pull/42)
> 
> Would you please update chart and reinstall it?
> 
> ```
> # update your crane version
> helm repo update
> 
> # uninstall
> helm uninstall crane -n crane-system
> 
> # install 
> helm install crane -n crane-system --create-namespace crane/crane
> ```

I tried but get new error.
```yaml
status:
  conditions:
  - lastTransitionTime: "2022-04-08T10:02:09Z"
    message: 'Failed to offer recommend, Recommendation default/abc-hpa-hpa-7zxkm:
      EHPAAdvisor prediction metrics data is unexpected, List length is 0 '
    reason: FailedOfferRecommend
    status: "False"
    type: Ready
  lastUpdateTime: "2022-04-08T10:02:09Z"
```
Is it prometheus's data is not enough？

**Comment by qmhu** [comment]
> 

yes, Time Series Prediction(For HPA recommendation) need at least 7 days running data for your cluster, and also it need your load to be predictable, for example like a wave.

The detail checking rule for HPA recommendation will be shown in docs which is coming soon.

**Comment by no-frown** [comment]
thinks
