### ISSUE TITLE
crane-agent start failed

### ISSUE THREAD

**Issue by justzx2011** [gocrane/crane#276]
k logs crane-agent-gnlzw -n crane-system
W0420 23:20:31.887538       1 manager.go:159] Cannot detect current cgroup on cgroup v2
I0420 23:20:31.890524       1 fs.go:131] Filesystem UUIDs: map[]
I0420 23:20:31.890779       1 fs.go:132] Filesystem partitions: map[/dev:{mountpoint:/dev major:0 minor:308 fsType:tmpfs blockSize:0} /dev/shm:{mountpoint:/dev/shm major:0 minor:324 fsType:tmpfs blockSize:0} /dev/vda1:{mountpoint:/dev/termination-log major:254 minor:1 fsType:ext4 blockSize:0} /proc/kcore:{mountpoint:/proc/kcore major:0 minor:308 fsType:tmpfs blockSize:0} /proc/keys:{mountpoint:/proc/keys major:0 minor:308 fsType:tmpfs blockSize:0} /proc/sched_debug:{mountpoint:/proc/sched_debug major:0 minor:308 fsType:tmpfs blockSize:0} /proc/timer_list:{mountpoint:/proc/timer_list major:0 minor:308 fsType:tmpfs blockSize:0} /rootvar/run/linuxkit-containerd/containerd.sock:{mountpoint:/rootvar/run/linuxkit-containerd/containerd.sock major:0 minor:23 fsType:tmpfs blockSize:0} /rootvar/run/linuxkit-external-logging.sock:{mountpoint:/rootvar/run/linuxkit-external-logging.sock major:0 minor:23 fsType:tmpfs blockSize:0} /run/secrets/kubernetes.io/serviceaccount:{mountpoint:/run/secrets/kubernetes.io/serviceaccount major:0 minor:298 fsType:tmpfs blockSize:0} /sys/firmware:{mountpoint:/sys/firmware major:0 minor:310 fsType:tmpfs blockSize:0} overlay_0-295:{mountpoint:/ major:0 minor:295 fsType:overlay blockSize:0} overlay_0-97:{mountpoint:/rootvar/run major:0 minor:97 fsType:overlay blockSize:0}]
I0420 23:20:31.891653       1 nvidia.go:54] NVIDIA GPU metrics disabled
E0420 23:20:31.893395       1 cadvisor_linux.go:76] Failed to create cadvisor manager start: could not detect clock speed from output: "processor\t: 0\nBogoMIPS\t: 48.00\nFeatures\t: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp flagm2 frint\nCPU implementer\t: 0x00\nCPU architecture: 8\nCPU variant\t: 0x0\nCPU part\t: 0x000\nCPU revision\t: 0\n\nprocessor\t: 1\nBogoMIPS\t: 48.00\nFeatures\t: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp flagm2 frint\nCPU implementer\t: 0x00\nCPU architecture: 8\nCPU variant\t: 0x0\nCPU part\t: 0x000\nCPU revision\t: 0\n\nprocessor\t: 2\nBogoMIPS\t: 48.00\nFeatures\t: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp flagm2 frint\nCPU implementer\t: 0x00\nCPU architecture: 8\nCPU variant\t: 0x0\nCPU part\t: 0x000\nCPU revision\t: 0\n\nprocessor\t: 3\nBogoMIPS\t: 48.00\nFeatures\t: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp flagm2 frint\nCPU implementer\t: 0x00\nCPU architecture: 8\nCPU variant\t: 0x0\nCPU part\t: 0x000\nCPU revision\t: 0\n\n"
E0420 23:20:33.897822       1 executor.go:41] GetRuntimeClient failed connect endpoint 'unix:///rootvar/run/dockershim.sock', make sure you are running as root and the endpoint has been started
E0420 23:20:35.900224       1 pod_resource_manger.go:53] GetRuntimeClient failed connect endpoint 'unix:///rootvar/run/dockershim.sock', make sure you are running as root and the endpoint has been started
I0420 23:20:36.107558       1 agent.go:90] Crane agent docker-desktop_42e5eaeb-c081-4c0a-a933-94ca8935a336 is starting
I0420 23:20:36.108160       1 analyzer.go:102] Starting anormaly analyzer.
I0420 23:20:36.108276       1 shared_informer.go:240] Waiting for caches to sync for anormaly-analyzer
I0420 23:20:36.108524       1 shared_informer.go:247] Caches are synced for anormaly-analyzer
I0420 23:20:36.108598       1 executor.go:63] Starting action executor.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x168edf8]

goroutine 1 [running]:
github.com/gocrane/crane/pkg/ensurance/executor.(*ActionExecutor).Run(0x0, 0xc0001ecf60)
	/go/src/github.com/gocrane/crane/pkg/ensurance/executor/executor.go:68 +0x78
github.com/gocrane/crane/pkg/agent.(*Agent).Run(0xc000114960, 0xc0000b2050, 0x0, {0x1c5e69b, 0xc})
	/go/src/github.com/gocrane/crane/pkg/agent/agent.go:93 +0x22f
github.com/gocrane/crane/cmd/crane-agent/app.Run({0x1ee5f10, 0xc000372780}, 0xc0003c4000)
	/go/src/github.com/gocrane/crane/cmd/crane-agent/app/agent.go:117 +0x68f
github.com/gocrane/crane/cmd/crane-agent/app.NewAgentCommand.func1(0xc0003d2280, {0x1c54544, 0x2, 0x2})
	/go/src/github.com/gocrane/crane/cmd/crane-agent/app/agent.go:59 +0x29
github.com/spf13/cobra.(*Command).execute(0xc0003d2280, {0xc00004c190, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003d2280)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/go/src/github.com/gocrane/crane/cmd/crane-agent/main.go:25 +0xaf

k8s version info : 
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/arm64"}

**Comment by lbbniu** [comment]
see: https://github.com/gocrane/crane/issues/232

**Comment by lbbniu** [comment]
This issue has been resolved, please close.
