### ISSUE TITLE
example for tsp cannot be executed properly

### ISSUE THREAD

**Issue by 13164815445** [gocrane/crane#306]
**Describe the bug**

example for tsp cannot be executed properly

**Reproduce steps**

install crane

modify tsp example tsp-workload-resource-dsp.yaml to our deployment and create

tsp status is always null

**Expected behavior**

tsp is stateful and has data

**Screenshots**

I added log and recompile updated Craned, the error log is 

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/16049916/167330782-47d70624-62e7-47a2-b730-9188ac9fb845.png">

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19] 1.18.10
 - Crane Version: [e.g. 0.1.0] 1.4
 - Browser [e.g. chrome, safari]  chrome

**Comment by 13164815445** [comment]
apiVersion: prediction.crane.io/v1alpha1
kind: TimeSeriesPrediction
metadata:
  name: xxxx
  namespace: xx-daily
spec:
  targetRef:
    kind: Deployment
    name: xxxx
    namespace: xx-daily
  predictionWindowSeconds: 3600
  predictionMetrics:
    - resourceIdentifier: workload-cpu
      type: ExpressionQuery
      expressionQuery:
        expression: 'sum(irate (container_cpu_usage_seconds_total{container="app",image!="",container!="POD",pod=~"^xxxx-.*$"}[1m]))by (pod) * 1000'
      algorithm:
        algorithmType: "dsp"
        dsp:
          sampleInterval: "60s"
          historyLength: "3d"
          estimators:
            fft:
              - marginFraction: "0.2"
                lowAmplitudeThreshold: "1.0"
                highFrequencyThreshold: "0.05"
                minNumOfSpectrumItems: 10
                maxNumOfSpectrumItems: 20
    - resourceIdentifier: workload-mem
      type: ExpressionQuery
      expressionQuery:
        expression: 'sum(container_memory_working_set_bytes{container="app",image!="", container!="POD",pod=~"^xxxx.*$"})by(pod)'
      algorithm:
        algorithmType: "dsp"
        dsp:
          sampleInterval: "60s"
          historyLength: "3d"
          estimators:
            fft:
              - marginFraction: "0.2"
                lowAmplitudeThreshold: "1.0"
                highFrequencyThreshold: "0.05"
                minNumOfSpectrumItems: 10
                maxNumOfSpectrumItems: 20

**Comment by lbbniu** [comment]
add apiVersion field
