### ISSUE TITLE
When an ehpa with a behavior is created, its corresponding hpa does not have a behavior

### ISSUE THREAD

**Issue by whitebear009** [gocrane/crane#310]
**Describe the bug**
When an ehpa with a behavior is created, its corresponding hpa does not have a behavior.

**Reproduce steps**
1.create an ehpa object
![image](https://user-images.githubusercontent.com/98402152/167629814-8ef10e83-eb84-42aa-a355-ed327d608d88.png)

2.  then an hpa object will be created, but without behavior
![image](https://user-images.githubusercontent.com/98402152/167629896-8aaf1458-f0b7-4e32-86d5-0540643c89a7.png)

**Expected behavior**
create an hpa object with behavior

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.18]
 - Crane Version: [e.g. 0.4.0]

**Comment by FTWH** [comment]
> I create a pull request to fix it. #311 Please check.

Could you please tell me how to enable EHPA of crane for a specific deployment under specific namespaces?
e.g. I have a deployment namely "nodeinfo" under namespaces "my-test".
I have tried the yaml offered by documentation, but can not find any config for namespaces.

**Comment by whitebear009** [comment]
@FTWH  you can create an EHPA under namespaces "my-test" （ the same with deployment) so it could be worked.
