### ISSUE TITLE
Agent does not start properly

### ISSUE THREAD

**Issue by ktvbcx** [gocrane/crane#313]
**Describe the bug**
Hi,I'm new to k8s and crane,and when I tried to install crane, the following error was reported. It seems that some components are not installed correctly,.Would you please help me to find out what the problem is?
**Reproduce steps**
helm repo add crane https://gocrane.github.io/helm-charts
helm install crane -n crane-system --create-namespace crane/crane
helm install fadvisor -n crane-system --create-namespace crane/fadvisor

**Expected behavior**
![image](https://user-images.githubusercontent.com/54368785/168035742-4fd883ca-e5c3-40e2-a55a-d4cade1990a0.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/54368785/168035701-3cd793f8-3f2b-4850-bf98-5f7232f91105.png)

**Environment (please complete the following information):**
 - K8S Version: 1.20.2
 - 
![image](https://user-images.githubusercontent.com/54368785/168035875-d7984512-022e-4286-b0a8-f20ce286f466.png)

 - Crane Version: latest

**Comment by zsnmwy** [comment]
There was something wrong with the "service craned".
Please show "service craned" in detail.
```shell
kubectl logs -n crane-system -p craned-xxx-xxx
```
```shell
kubectl get svc -n crane-system
```
---

Fail: crane-agent == **webhook** ==> craned

---
How about joining the WeChat group? It is easy for us to exchange information.

**Comment by ktvbcx** [comment]
> There was something wrong with the "service craned". Please show "service craned" in detail.
> 
> ```shell
> kubectl logs -n crane-system -p craned-xxx-xxx
> ```
> 
> ```shell
> kubectl get svc -n crane-system
> ```
> 
> Fail: crane-agent == **webhook** ==> craned
> 
> How about joining the WeChat group? It is easy for us to exchange information.
Thank you a log for your help,i have tried by your command and find out the reason is that i didn't deploy prometheus and grafana by the way the doc show,but i have deploy them before in other ns. I will try Customize Installation again,thank you.

**Comment by zsnmwy** [comment]
ref issues https://github.com/gocrane/crane/pull/312
