### ISSUE TITLE
设置cron及外部指标后缩容异常

### ISSUE THREAD

**Issue by saikey0379** [gocrane/crane#362]
**Describe the bug**
设置计划任务进行定时扩容，计划任务完成后，副本数未按外部指标进行相应缩容

**Reproduce steps**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/41617636/174047098-466a449b-0426-4e9a-b9da-1561f9d18d38.png)
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/41617636/174047429-518cddc5-fb8b-470b-a428-0c1abff6d203.png">

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]

**Comment by qmhu** [comment]
We need to support remote adapter for external metric to resolve this.
