### ISSUE TITLE
metric crane_pod_cpu_usage no predict data

### ISSUE THREAD

**Issue by MarkyMark4120** [gocrane/crane#366]
**Describe the bug**
After deploying EHPA on a local cluster, the status condition type of "PredictionReady" indicates that metric crane_pod_cpu_usage no predict data. 
When I checked crane-agent logs, it shows 
1 node_resource_manager.go:314] Can't get cpu_total_usage from NodeResourceManager local state.
Also, the prediction metrics in EHPA's yaml isn't converted to metrics in HPA yaml file. Only the default cpu utilization metric is present in the HPA yaml.

**Reproduce steps**
* deploy php-apache sample
* edit ehpa yaml file to change ScaleTargetRef to php-apache
* apply ehpa yaml file

**Expected behavior**

**Screenshots**
ehpa status:
![ehpa](https://user-images.githubusercontent.com/48610618/174323301-18e1eebe-2e30-4c0f-896f-f1e2cc5c6a5c.png)
hpa:
![hpa](https://user-images.githubusercontent.com/48610618/174323369-ea39bede-32e5-4c80-9476-d05f48cbb1c0.png)
crane-agent logs:
![crane-agent logs](https://user-images.githubusercontent.com/48610618/174323431-14fba77c-c174-4171-8b56-71b2a73af06c.png)

**Environment (please complete the following information):**
 - K8S Version: [1.23.6]
 - Crane Version: [0.5.0]
 - Laptop Processor Type:[darwin/arm64]

**Comment by qmhu** [comment]
From you screenshot, I can found the error "crane_pod_cpu_usage no predict data."

related docs: https://github.com/gocrane/crane/blob/main/docs/tutorials/using-effective-hpa-to-scaling-with-effectiveness.zh.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by MarkyMark4120** [comment]
> 
Hi, I think the error message is in the first screenshot. It's located at `status.conditions[1].message` of the EHPA status. Is this error message related to the link above?

**Comment by MarkyMark4120** [comment]
What's the average wait time for crane_pod_cpu_usage to be ready?
