### ISSUE TITLE
Translate README.md to Chinese

### ISSUE THREAD

**Issue by qmhu** [gocrane/crane#372]
将根目录的README.md翻译成中文

**Comment by zsnmwy** [comment]
我已完成对README.MD的翻译（简体中文）
[README_CN.md](https://github.com/gocrane/crane/files/8990870/README_CN.md)

_Originally posted by @QiuToo in https://github.com/gocrane/crane/issues/377#issuecomment-1167148179_

---

Can you send a pr with these changes?
You can follow [this guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) to create a pull request if you are new to GitHub.

**Comment by 2783945952** [comment]
nice
