### ISSUE TITLE
Question About Prediction Algorithm

### ISSUE THREAD

**Issue by warrenincn** [gocrane/crane#383]

**Comment by yufeiyu** [comment]
The DSP prediction

**Comment by warrenincn** [comment]
According to the article,  dsp has 7 configurations， is there any best practice guide to make those configurations accurate?

**Comment by yufeiyu** [comment]
> According to the article, dsp has 7 configurations， is there any best practice guide to make those configurations accurate?

Good point. Such a guide will be provided later.
