### ISSUE TITLE
我们怎么知道资源费用的呐？

### ISSUE THREAD

**Issue by yongxinzhang18810492456** [gocrane/crane#413]
![image](https://user-images.githubusercontent.com/33047172/179144550-17795090-6cba-4a51-8bbc-200dbd1f0756.png)

**Comment by qmhu** [comment]
Fadvisor(FinOps Advisor) provides capability of FinOps Observalibility, it can be integrated with Crane to help users to improve the cost visualization and cost optimization. Also, it can be integrated with your monitoring system as a metric exporter.

We use a default pricing value to calculate the cost which is based on tencent cloud's price. If you want to calculate the price based on real-time pricing api, you can referring to this document.

https://github.com/gocrane/fadvisor#deploy-on-cloud
