### ISSUE TITLE
Craned updates resources in apiserver too frequently

### ISSUE THREAD

**Issue by yufeiyu** [gocrane/crane#443]
**Describe the bug**
A user integrates crane with ArgoCD and finds that crane updates resources in apiserver so frequently and the frontend of argocd receives resource update messages, as a result the frontend of argocd gets stuck.

**Reproduce steps**

**Expected behavior**

**Screenshots**
<img width="1416" alt="企业微信截图_a7d8630f-7230-451f-a56c-7424df5efa09" src="https://user-images.githubusercontent.com/3377622/181451059-c2f4c012-e3e6-40f6-87d6-a92db81cd220.png">
<img width="1314" alt="企业微信截图_9cf785dc-8df4-4ce2-a833-2c21f2f60093" src="https://user-images.githubusercontent.com/3377622/181451090-65c51d67-6e0b-4a60-b52e-4150e1af1b70.png">
<img width="1575" alt="企业微信截图_45857bb7-cfac-48b9-b206-2dd719800de5" src="https://user-images.githubusercontent.com/3377622/181451105-68c8564f-0da8-4e1a-aac5-d4b4e71a041d.png">

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]

**Comment by qmhu** [comment]
Would you please provide more detail, for example HPA count and HPA update frequency.
