### ISSUE TITLE
docs: fail to get file content from mirror repo

### ISSUE THREAD

**Issue by zsnmwy** [gocrane/crane#447]
**Describe the bug**
<img width="427" alt="image" src="https://user-images.githubusercontent.com/35299017/182189138-1bf9aa35-8706-496a-a626-61f2149f1a39.png">
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/35299017/182189173-4e13161e-ae14-4270-8483-8aca62e9f8e4.png">

**Comment by qmhu** [comment]
So should we move to another mirror ?
