### ISSUE TITLE
Developer' Guide

### ISSUE THREAD

**Issue by qmhu** [gocrane/crane#459]
Crane need a Developer's Guide document to let new craner to know how to contribute code.

The document might include informations like:

- How to clone the project.
- How to build binary and images from code
- How to prepare local environments (Optional)

related doc: https://github.com/gocrane/crane/tree/main/pkg/web

**Comment by YashPimple** [comment]
@qmhu Can you assign this issue to me . I would like to work on it .

**Comment by qmhu** [comment]
> @qmhu Can you assign this issue to me . I would like to work on it .

Done. Expect to see it soon 👍

**Comment by YashPimple** [comment]
Sure👍🏻

**Comment by JaneConan** [comment]
「weopen star」I would like to work on it, too~ THX😊

**Comment by qmhu** [comment]
> 「weopen star」I would like to work on it, too~ THX😊

Also assign it to you. 👍
