### ISSUE TITLE
Introduce describe

### ISSUE THREAD

**Issue by wangfeng1983** [gocrane/crane#460]
**Describe the bug**
one-stop-shop or one-step-shop？
**Reproduce steps**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/98692607/183352030-d0f59ae2-bce9-4103-a1f0-768920b71387.png)

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]

**Comment by qmhu** [comment]
one-stop-shop -> 一站式服务
