### ISSUE TITLE
template/scheduler-deployment.yaml has extra spaces

### ISSUE THREAD

**Issue by xzclinux** [gocrane/crane#470]
Error: YAML parse error on scheduler/templates/scheduler-deployment.yaml: error converting YAML to JSON: yaml: line 24: could not find expected ':'

**Comment by xzclinux** [comment]
As shown in the figure below, it can be solved as shown

**Comment by xzclinux** [comment]
As shown in the figure below, it can be solved as shown
![image](https://user-images.githubusercontent.com/75306994/184092763-05de63d0-074d-443f-979e-c5eb9c1bd7e9.png)

![image](https://user-images.githubusercontent.com/75306994/184092733-ec595fb8-408a-4f0f-b765-170d2cf79e6d.png)

**Comment by qmhu** [comment]
Hi @xzclinux :

You can bump up the chart version for crane-scheduler to fix it actually.

**Comment by qmhu** [comment]
https://github.com/gocrane/helm-charts/pull/72
fixed
