### ISSUE TITLE
本机docker环境k8s集群下，获取推荐配置报错

### ISSUE THREAD

**Issue by pythonsoft** [gocrane/crane#486]
环境：win-10或mac  docker k8s-for-docker

现象：按照 推荐配置 文档获取推荐配置，提示  Failed to offer recommendation: no enough metrics
![image](https://user-images.githubusercontent.com/3001005/185123569-f5dcdac6-412e-445a-91b7-271208ce65c7.png)

**Comment by zsnmwy** [comment]
应当是recommend需要的数据不够，需要再等等。
