### ISSUE TITLE
Move API definitions from crane-scheduler to api repo

### ISSUE THREAD

**Issue by mfanjie** [gocrane/crane#488]
## Describe the feature
crane-scheduler has some api types defined in `pkg/plugins/apis/policy`, those api should be moved to api repo which is a centralized model repo.
Hence we need some help to move api types from crane-scheduler to api, and make those apis being imported to crane-scheduler repo as a go module.

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help

**Comment by mfanjie** [comment]
Thanks for the help @mangoGoForward
