### ISSUE TITLE
Craned crashloopbackoff after upgrading to 0.7.0

### ISSUE THREAD

**Issue by wswz963852** [gocrane/crane#532]
Container log before restart is as follows:

I0826 15:26:39.323923       1 effective_hpa_controller.go:126] Updated ehpa elk/logstash-k8s-elk-ehpa current metrics: - pods:
    current:
      averageValue: 204m
    metric:
      name: crane_pod_cpu_usage
      selector:
        matchLabels:
          autoscaling.crane.io/effective-hpa-uid: 158d30b0-6553-4620-b6ca-776b8dbf33b0
  type: Pods
- resource:
    current:
      averageUtilization: 27
      averageValue: 81m
    name: cpu
  type: Resource
.
I0826 15:26:39.339927       1 effective_hpa_controller.go:164] Update EffectiveHorizontalPodAutoscaler status successful, ehpa elk/logstash-k8s-elk-ehpa
E0826 15:26:40.182957       1 manager.go:399] failed to wait for recommendationrule caches to sync: timed out waiting for cache to be syncedproblem running crane manager
F0826 15:26:40.182974       1 manager.go:400] failed to wait for recommendationrule caches to sync: timed out waiting for cache to be synced

**Environment
 - K8S Version: 1.21
 - Crane Version: 0.7.0

**Comment by qmhu** [comment]
The error is lack of crd definitions. You need to apply new crds for your cluster.
You can referring to the upgrade steps in release note: https://github.com/gocrane/crane/releases/tag/v0.7.0

**Comment by wswz963852** [comment]
Thanks for the help.
