### ISSUE TITLE
[BUG]metric-adapter cannot find model definition for k8s.io/apimachinery/pkg/version.Info

### ISSUE THREAD

**Issue by saikey0379** [gocrane/crane#558]
**Describe the bug**
build metric-adapter from main code

**Reproduce steps**
start error

**Expected behavior**

**Screenshots**
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/41617636/190599588-e6bffc89-ff96-496f-809f-1cb02df75e76.png">
**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]

**Comment by qmhu** [comment]
resolve it in latest gocrane/api
