### ISSUE TITLE
crane agent log print GetContainerInfoV2 failed

### ISSUE THREAD

**Issue by zj452008181** [gocrane/crane#559]
**version**:
crane 0.7

**question**:
crane-agent logs:
 E0916 10:07:58.940423       1 cadvisor_linux.go:126] GetContainerInfoV2 failed: unknown container: "/kubepods/burstable/podd5220937-6392-47fc-8008-a7b051f80062"

 E0916 10:07:58.940515       1 cadvisor_linux.go:126] GetContainerInfoV2 failed: unknown container: "/kubepods/burstable/pod01b0eaa4-1174-4f50-b161-a3993542f1d3"

 E0916 10:07:58.940571       1 cadvisor_linux.go:126] GetContainerInfoV2 failed: unknown container: "/kubepods/burstable/pod9542c877-171c-4aa4-8405-0c56d1842ab7"

 E0916 10:07:58.940629       1 cadvisor_linux.go:126] GetContainerInfoV2 failed: unknown container: "/kubepods/burstable/podd44c1538-07d7-4f43-8bd0-3f68b6cf2e24"

 E0916 10:07:58.940678       1 cadvisor_linux.go:126] GetContainerInfoV2 failed: unknown container: "/kubepods/besteffort/podc58869c2-6b26-4b2f-803e-dc7460546a9f"

 E0916 10:07:58.940729       1 cadvisor_linux.go:126] GetContainerInfoV2 failed: unknown container: "/kubepods/burstable/poda28767fa-bc91-4572-86f0-ab5b229f7d15"

 E0916 10:07:58.940771       1 cadvisor_linux.go:126] GetContainerInfoV2 failed: unknown container: "/kubepods/burstable/pod73e2e4c5-9a99-4934-a5bc-2f6c95560c04"

 E0916 10:07:58.940809       1 cadvisor_linux.go:126] GetContainerInfoV2 failed: unknown container: "/kubepods/burstable/pod6e178451-6ea3-4fa5-bd47-fa852c8290c6"

**Comment by mfanjie** [comment]
This is a debug log of cadvisor, the reason of this error is crane agent collect state by cadvisor in 10s interval, if a pod is being created, and if the cgroup folder is not ready, cadvisor would print such information. it's not an issue.
