### ISSUE TITLE
recommendedValue is empty

### ISSUE THREAD

**Issue by QuchengRep1** [gocrane/crane#566]
## Describe the feature
Version : craned:v0.3.0

When I use a Analytics with type: Replicas，Recommendation returns ready but I got no  recommendedValue.

That 's all status show:
status:
  conditions:
  - lastTransitionTime: "2022-09-22T10:07:09Z"
    message: Recommendation is ready
    reason: RecommendationReady
    status: "True"
    type: Ready

Then I turn down the config  in Analytics.spec.config:
  config:
    ehpa.deployment-min-replicas: "0"
    ehpa.statefulset-min-replicas: "0"
    ehpa.workload-min-replicas: "0"
    ehpa.pod-min-ready-seconds: "0"
    ehpa.pod-available-ratio: "0"
    ehpa.default-min-replicas: "0"
    ehpa.min-cpu-usage-threshold: "0"
    ehpa.fluctuation-threshold: "0"
    ehpa.min-cpu-target-utilization: "0"

But its not work yet, situation is the same as before，Recommendation returns ready and 
 got no Recommendation.status.recommendedValue in result.

**Comment by qmhu** [comment]
Would you please upgrade to newest version:0.7 ? https://github.com/gocrane/crane/releases/tag/v0.7.0
Analytics in 0.3 is not working ready yet,
