### ISSUE TITLE
按照官方教程安装失败

### ISSUE THREAD

**Issue by cookdrinker** [gocrane/crane#589]
**Describe the bug**
按照官网方法安装时出现异常报错，安装中断。
[root@hz-sd-qingzhou-dev2-08 tmws]# helm install crane -n crane-system --create-namespace crane/crane
I1024 15:34:28.730965    1225 request.go:621] Throttling request took 1.176756537s, request: GET:https://ccnp.c2m-mom.com:6443/apis/cluster.kubesphere.io/v1alpha1?timeout=32s
Error: rendered manifests contain a resource that already exists. Unable to continue with install: APIService "v1beta1.external.metrics.k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "crane"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "crane-system"

**Reproduce steps**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17402076/197473239-e42297cc-b985-4bce-93ab-5e9da065132d.png)

**Environment (please complete the following information):**
 - K8S Version: [v1.21.8]
 - Crane Version: [0.8.0]

**Comment by qmhu** [comment]
参考安装文档中的常见问题：https://gocrane.io/zh-cn/docs/getting-started/installation/#%E8%8E%B7%E5%8F%96-crane-url-%E7%9A%84%E5%85%B6%E5%AE%83%E6%96%B9%E5%BC%8F

你的集群中external metric api冲突了，可以先删除它再继续安装：
`kubectl delete apiservice v1beta1.external.metrics.k8s.io`

**Comment by qmhu** [comment]
common question
