### ISSUE TITLE
如何使用外置的grafana

### ISSUE THREAD

**Issue by vb3328998** [gocrane/crane#596]
grafana面板是部署在集群内的不同命名空间下，如何接入到crane里面，我看helm的values配置也没有相应的配置路径

**Comment by vb3328998** [comment]
![image](https://user-images.githubusercontent.com/40584745/198982444-b06858d7-3bbb-404c-819a-c8aca776216c.png)

**Comment by zhuw0312** [comment]
同问

**Comment by zsnmwy** [comment]
Dashboard的设计与常规的前后端分离是相似的。

可以尝试修改nginx配置，流量导向真正使用的Grafana。

这是一个Configmap，改完后，直接重建POD即可生效。

https://github.com/gocrane/crane/blob/8d552faf36f8c35cdd55c45dc47e229f3cb230eb/deploy/craned/deployment.yaml#L226-L231

https://github.com/gocrane/crane/blob/8d552faf36f8c35cdd55c45dc47e229f3cb230eb/deploy/craned/deployment.yaml#L78-L80

**Comment by zhuw0312** [comment]
> Dashboard的设计与常规的前后端分离是相似的。
> 
> 可以尝试修改nginx配置，将流量导向真正使用的Grafana。
> 
> 这是一个Configmap，改完后，直接重建POD即可生效。
> 
> https://github.com/gocrane/crane/blob/8d552faf36f8c35cdd55c45dc47e229f3cb230eb/deploy/craned/deployment.yaml#L226-L231
> 
> https://github.com/gocrane/crane/blob/8d552faf36f8c35cdd55c45dc47e229f3cb230eb/deploy/craned/deployment.yaml#L78-L80

这样的话，在成本分析里找不到那3个dashboard，应该怎么做呢请问？

**Comment by qmhu** [comment]
> > Dashboard的设计与常规的前后端分离是相似的。
> > 可以尝试修改nginx配置，将流量导向真正使用的Grafana。
> > 这是一个Configmap，改完后，直接重建POD即可生效。
> > https://github.com/gocrane/crane/blob/8d552faf36f8c35cdd55c45dc47e229f3cb230eb/deploy/craned/deployment.yaml#L226-L231
> > 
> > https://github.com/gocrane/crane/blob/8d552faf36f8c35cdd55c45dc47e229f3cb230eb/deploy/craned/deployment.yaml#L78-L80
> 
> 这样的话，在成本分析里找不到那3个dashboard，应该怎么做呢请问？

可以提供更详细的操作步骤和环境信息吗

**Comment by zhuw0312** [comment]
> > > Dashboard的设计与常规的前后端分离是相似的。
> > > 可以尝试修改nginx配置，将流量导向真正使用的Grafana。
> > > 这是一个Configmap，改完后，直接重建POD即可生效。
> > > https://github.com/gocrane/crane/blob/8d552faf36f8c35cdd55c45dc47e229f3cb230eb/deploy/craned/deployment.yaml#L226-L231
> > > 
> > > https://github.com/gocrane/crane/blob/8d552faf36f8c35cdd55c45dc47e229f3cb230eb/deploy/craned/deployment.yaml#L78-L80
> > 
> > 
> > 这样的话，在成本分析里找不到那3个dashboard，应该怎么做呢请问？
> 
> 可以提供更详细的操作步骤和环境信息吗

```
location /grafana {
            set $upstream_grafana grafana.monitoring.svc.cluster.local:3000;
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_pass http://$upstream_grafana;
            proxy_redirect off;
            #rewrite /grafana/(.*) /$1 break;
            proxy_http_version 1.1;
            proxy_set_header  Host $http_host;
            proxy_set_header  Upgrade $http_upgrade;
            proxy_set_header  Connection $connection_upgrade;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```
上面是nginx-conf对于集群里已有的grafana配置。但是在crane的dashabord看不到namespace-costs 3个dashboard（请看附件）。还有一个问题是调用已有的prometheus-adapter 只要配置remotepadapter就好了么？
![QQ截图20221102151332](https://user-images.githubusercontent.com/10015120/199423818-c8c30b4d-cfe3-4626-bb79-677e320f15a4.png)

**Comment by qmhu** [comment]
打开浏览器的“开发者工具”看下这里有什么报错，把错误信息贴出来

**Comment by vb3328998** [comment]
![image](https://user-images.githubusercontent.com/40584745/199871150-cb60879a-516a-4b7d-9b79-ea6420f432d5.png)
这里少了2个数据，需要怎么排查呢，不知道出自哪张表

**Comment by vb3328998** [comment]
> 打开浏览器的“开发者工具”看看下这里有什么报错，把错误信息贴出来

这个是报了401的错误，默认密码账号都是admin

**Comment by qmhu** [comment]
> > > 打开浏览器的“开发者工具”看看下这里有什么报错，把错误信息贴出来
> > 
> > 
> > 这个是报了401的错误，默认密码是admin
> 
> 自建的grafana账号密码去哪里配置呢

grafana嵌入dashboard需要grafana满足一定的配置才可以，相关配置我发到下面了，同时看到页面上显示“No Data”，那么你自己的prometheus配置的应该也不对，所以最好检查下crane的配置中 PROMETHEUS-ADDRESS 的配置。

https://github.com/gocrane/helm-charts/blob/main/integration/grafana/override_values.yaml

**Comment by vb3328998** [comment]
> > > > 打开浏览器的“开发者工具”看看下这里有什么报错，把错误信息贴出来
> > > 
> > > 
> > > 这是报了401的错误，默认密码是admin
> > 
> > 
> > 自建的grafana账号去哪里配置呢
> 
> grafana嵌入所以检查dashboard需要grafana满足一定的配置才可以，相关配置我发到，同时看到页面上显示“No Data”，下面你自己的prometheus配置的也不应该对，最好下crane的配置中 PROMEHEUS-ADDRESS 的配置。
> 
> https://github.com/gocrane/helm-charts/blob/main/integration/grafana/override_values.yaml

grafana的账号密码是admin是前提吗？我已经把grafana的表格迁移到自己的grafana里面了，同时也把prometheus的job也迁移到自己的prometheus，现在只缺这2个数据，想要补充他，该如何排查是哪个的问题，PROMEHEUS-ADDRESS也是对应了自己的prometheus
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/40584745/200122604-a07a46ca-cdd2-4ae1-ba74-f74b1a96a58d.png">

**Comment by qmhu** [comment]
这里没数据是因为没有采集到fadvisor的metric，参考下面配置设置下：

https://github.com/gocrane/helm-charts/blob/main/integration/prometheus/override_values.yaml#L56

**Comment by vb3328998** [comment]
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/40584745/200123942-575ac20e-15d8-456b-b0e7-7291ebd8dea2.png">
我这里是正常采集到的
还有补充下刚才的错误，我已经把grafana三张图表import到自己的grafana上了，但是我自己的grafana是能对外访问的，密码不能设置得那么简单，该如何配置dashborad里面的grafana账号密码

> > > > > 打开浏览器的“开发者工具”看看下这里有什么报错，把错误信息贴出来
> > > > 
> > > > 
> > > > 这是报了401的错误，默认密码是admin
> > > 
> > > 
> > > 自建的grafana账号去哪里配置呢
> > 
> > 
> > grafana嵌入所以检查dashboard需要grafana一定的配置才可以，配置我发到，同时看到页面上显示“No Data”，下面相关的是你自己的prometheus配置的也不应该对，最好下crane的配置中PROMEHEUS-ADDRESS 的配置。
> > https://github.com/gocrane/helm-charts/blob/main/integration/grafana/override_values.yaml
> 
> 我已经把自己的密码转移到了自己的密码里怎么排查是哪个问题，PROMEHEUS-ADDRESS也是自己的prometheus <img alt="图片" width="1015" src="https://user-images.githubusercontent.com/40584745/200122604-a07a46ca-cdd2-4ae1-ba74-f74b1a96a58d.png">

**Comment by vb3328998** [comment]
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/40584745/200125120-6d63d27c-04b9-4211-8fda-8d71d745fab3.png">
我想我应该知道问题了，之前我的vm查不到记录规则，直到我去掉这个|之后才能查询到
<img width="900" alt="image" src="https://user-images.githubusercontent.com/40584745/200125184-6285d967-3392-4f95-8f45-173113976a5e.png">
这里的数据是一个小时会去刷新一次吗？我看interval也是3600秒去抓取一次记录规则，现在还是显示no data。
-----------------------------------------
现在主要的问题就是外置grafana401的问题，如何设置dashboard连接grafana时的账号密码

**Comment by vb3328998** [comment]
![image](https://user-images.githubusercontent.com/40584745/200219494-c6cf7530-f03f-4213-8c89-25f1e5d0e70b.png)
目前我看还是no data，检查得知这里的100.少了个0,vitoriametrics少个零是查询不到的，grafana已经修改成100.0，并且grafana显示正常，但是这里却还是提示是100.
![image](https://user-images.githubusercontent.com/40584745/200219808-55ce2b34-cc4f-47b4-8559-a64b02db13ed.png)
还有一些是没显示数据

**Comment by qmhu** [comment]
> 

可以本地启动dashboard调试下.参考下本地web的文档： https://github.com/gocrane/crane/tree/main/pkg/web

**Comment by qmhu** [comment]
@zsnmwy How do we config the grafana account when dashboard embed it?
