### ISSUE TITLE
Hyperlink of slack in README file is no longer active

### ISSUE THREAD

**Issue by niconical** [gocrane/crane#600]
**Describe the bug**
The slack hyperlink in the readme file has expired, I cannot use this hyperlink to join the community.

**Reproduce steps**
Just click the slack hyperlink

**Expected behavior**

After clicking the hyperlink, users should be able to jump to the slack app as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/23325508/199186622-bdf8dc9f-91c1-425c-a545-d0f772ed06aa.png)

**Environment (please complete the following information):**
 - Browser [Microsoft Edge]

**Comment by qmhu** [comment]
@niconical  resolved, please feel free to chat with us in slack.

**Comment by niconical** [comment]
> @niconical resolved, please feel free to chat with us in slack.

Thanks.
