### ISSUE TITLE
question about provider

### ISSUE THREAD

**Issue by zhuw0312** [gocrane/crane#601]
请问default provider是特指腾讯云么？还是说适配所有？

**Comment by qmhu** [comment]
The default cloud provider is for tencent cloud. But, if you have requirements for other clouds like AWS, or you want to implements a cloud provider , we'd like to make it happen.

**Comment by zhuw0312** [comment]
> The default cloud provider is for tencent cloud. But, if you have requirements for other clouds like AWS, or you want to implements a cloud provider , we'd like to make it happen.

i want to  implements  huaweicloud and aliyun.how long will it happen ?

**Comment by qmhu** [comment]
> > The default cloud provider is for tencent cloud. But, if you have requirements for other clouds like AWS, or you want to implements a cloud provider , we'd like to make it happen.
> 
> i want to implements huaweicloud and aliyun.how long will it happen ?

you can add my wechat:huqiming2183
