### ISSUE TITLE
对接集群外的prometheus指标查询数据为空

### ISSUE THREAD

**Issue by dbaicss** [gocrane/crane#602]
## Describe the feature
dashboard里面的当月总成本，预估成本查询数据为空
node:node_total_hourly_cost:avg[30d]这个指标可能是record，请问下node_total_hourly_cost这个指标查询的expr是什么，在哪里配置的

**Comment by qmhu** [comment]
Fadvisor通过计算集群中的资源和计费api得到费用的metric，比如你提到的node_total_hourly_cost，再通过prometheus抓取存储起来。因此，你可以检查下prometheus的抓取过程是否成功，在crane的helm-chart中我们提供了一份配置，你可以参考下：

[node_total_hourly_cost](https://github.com/gocrane/helm-charts/blob/main/integration/prometheus/override_values.yaml#L64)
