### ISSUE TITLE
failed to sync this node

### ISSUE THREAD

**Issue by vb3328998** [gocrane/crane#603]
scheduler-controller提示failed to sync this node ["10.88.123.175/cpu_usage_max_avg_1d"]: can not annotate node
原因是prometheus记录的规则没数据
要怎么解决这个问题呢

**Comment by xieydd** [comment]
Does your prometheus have this metrics name `cpu_usage_max_avg_1d ` in the prometheus rule? @vb3328998

**Comment by vb3328998** [comment]
有这个指标名称，我找到原因了，默认安装的prometheus的node exporter 规则有问题，已经解决了，谢谢
