### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by francis-jjk** [gocrane/crane#604]
➜  ~ helm install crane -n crane-system --create-namespace crane/crane
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: APIService "[v1beta1.custom.metrics.k8s.io](http://v1beta1.custom.metrics.k8s.io/)" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "[app.kubernetes.io/managed-by](http://app.kubernetes.io/managed-by)": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "crane"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "crane-system"

**Comment by qmhu** [comment]
Hi francis:

Please refer to documents: https://gocrane.io/zh-cn/docs/getting-started/installation/#%E5%AE%89%E8%A3%85-crane-%E6%8A%A5%E9%94%99

**Comment by francis-jjk** [comment]
Stil doesn't work
![image](https://user-images.githubusercontent.com/110971964/200247029-96d1b02c-915e-411c-a1dd-7b59a8a4d734.png)

**Comment by francis-jjk** [comment]
How can i get  the result as your doc says
![image](https://user-images.githubusercontent.com/110971964/200247313-dc2e6175-a805-4703-8f52-c435bd36f04e.png)

**Comment by qmhu** [comment]
> How can i get the result as your doc says ![image](https://user-images.githubusercontent.com/110971964/200247313-dc2e6175-a805-4703-8f52-c435bd36f04e.png)

Please make sure your helm repo is newest.  You can use this cmd to update it:

```
helm repo update
```

**Comment by qmhu** [comment]
> Stil doesn't work ![image](https://user-images.githubusercontent.com/110971964/200247029-96d1b02c-915e-411c-a1dd-7b59a8a4d734.png)

Seems you used existing prometheus, so please check the docs here https://gocrane.io/zh-cn/docs/getting-started/installation/#%E4%BD%BF%E7%94%A8%E5%A4%96%E9%83%A8%E7%9A%84-prometheus%E5%8F%AF%E9%80%89

**Comment by qmhu** [comment]
@francis-jjk Is your problem resolved?
