### ISSUE TITLE
使用自有Prometheus+Grafana， Grafana及crane看板没有数据。请指导！

### ISSUE THREAD

**Issue by xinsir88** [gocrane/crane#606]
老师您好：
       我使用我们本地的Prometheus+Grafana，做了如下操作：
           1.在values.yaml文件中更改了Prometheus的地址；
           2.在craned-deployment.yaml文件中更改了Grafana地址；
           3.使用url:port/grafana可以正常跳转到Grafana页面；
           4.Prometheus Crane、crane-agent、fadvisor三个的targets，状态均正常。
问题：
           Crane看板及Grafana看不到数据，如下图：
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/44859018/200212232-7dde4900-831c-4be3-8c6e-dac854f82c86.png">
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/44859018/200212261-104b245f-2526-4f21-83d9-52fd3ee44f6a.png">

**Comment by xinsir88** [comment]
有没有大佬给指点下？实在不知道是哪的问题了。
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/44859018/200216069-e833f9b9-c13e-4391-9715-4ae933d20fa5.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/44859018/200216088-bcaba948-d491-4a9e-9dec-9859306091d3.png">

**Comment by vb3328998** [comment]
get cm看下，有个nginx-conf的配置，里面可以配置grafana的地址
![image](https://user-images.githubusercontent.com/40584745/200219288-567d669c-bbd4-40ae-a08a-9f88c9e0c657.png)

**Comment by xinsir88** [comment]
这个我已经配置了， 我自己在Grafana上的图可以看到， crane相关的3个Dashbord看不到。 
<img width="680" alt="image" src="https://user-images.githubusercontent.com/44859018/200225245-98d04f12-d331-4064-bab7-577b03ed66a7.png">
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/44859018/200225340-50a1bce3-c61c-4eef-92e7-953d992a6a6d.png">
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/44859018/200225454-6401b5d2-8310-4c19-bfba-37e421896950.png">
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/44859018/200225499-6ae0a057-4f47-45dc-9327-86eb9044f405.png">

**Comment by vb3328998** [comment]
你用的同样是prometheus吗？还是其他的？我用的vm，需要调整一下 job_name 的规则

**Comment by xinsir88** [comment]
是的， 用的也是Prometheus，Job_name需要调整那块？ 能不能给指出下？

**Comment by xinsir88** [comment]
哪位大哥 能给指导下？

**Comment by qmhu** [comment]
> 哪位大哥 能给指导下？

先尝试解决下没有监控数据的问题。从上面prometheus的target中看到crane的组件都能看到状态了，如果prometheus能正常采集这些组件的metric，那么dashboard没有监控数据的原因可以先尝试看下craned中的prometheus-address是否正确。

检查下craned的yaml中PROMETHEUS_ADDRESS的地址是否指向你环境的prom，格式是http://{your-address:port}
```
command:
    - /craned
    - --prometheus-address=PROMETHEUS_ADDRESS
    - --feature-gates=Analysis=true,TimeSeriesPrediction=true,Autoscaling=true
    - --recommendation-configuration-file=/tmp/recommendation-config/config.yaml
    - -v=4
```

**Comment by qmhu** [comment]
如果prometheus- address不正确，从craned的日志中也能看到一些错误，如果上面的问题没解决，也可以贴下craned的日志。

**Comment by xinsir88** [comment]
> > 哪位大哥 能给指导下？
> 
> 先尝试解决下没有监控数据的问题。从上面prometheus的target中看到crane的组件都能看到状态了，如果prometheus能正常采集这些组件的metric，那么dashboard没有监控数据的原因可以先尝试看下craned中的prometheus-address是否正确。
> 
> 检查下craned的yaml中PROMETHEUS_ADDRESS的地址是否指向你环境的prom，格式是http://{your-address:port}
> 
> ```
> command:
>     - /craned
>     - --prometheus-address=PROMETHEUS_ADDRESS
>     - --feature-gates=Analysis=true,TimeSeriesPrediction=true,Autoscaling=true
>     - --recommendation-configuration-file=/tmp/recommendation-config/config.yaml
>     - -v=4
> ```

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/44859018/200247116-10fd40f8-e779-4d2a-be4e-15a6f24354c4.png">
Prometheus地址是我的地址，没有问题的。

**Comment by xinsir88** [comment]
> 如果prometheus- address不正确，从craned的日志中也能看到一些错误，如果上面的问题没解决，也可以贴下craned的日志。

[craned.log](https://github.com/gocrane/crane/files/9948978/craned.log)

**Comment by qmhu** [comment]
在craned容器内可以访问http://192.168.223.135:32667吗？

curl http://192.168.223.135:32667

**Comment by xinsir88** [comment]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/44859018/200261859-05c9ef5d-35db-4f7f-bfe8-6e0374a6ade1.png">
可以通的， 不过容器内没有安装curl，所以我没curl。 上图是ping的。大佬

> 在craned容器内可以访问[http://192.168.223.135:32667吗？](http://192.168.223.135:32667%E5%90%97%EF%BC%9F)
> 
> curl http://192.168.223.135:32667

**Comment by qmhu** [comment]
> <img alt="image" width="981" src="https://user-images.githubusercontent.com/44859018/200261859-05c9ef5d-35db-4f7f-bfe8-6e0374a6ade1.png">
> 
> 可以通的， 不过容器内没有安装curl，所以我没curl。 上图是ping的。大佬
> > 在craned容器内可以访问[http://192.168.223.135:32667吗？](http://192.168.223.135:32667%E5%90%97%EF%BC%9F)
> > curl http://192.168.223.135:32667

当集群导入到dashboard后，资源推荐可以正常显示一些推荐结果吗，如果不行，那么很可能是prometheus的问题。

首先你可以通过quick start快速搭建一套本地的all in one环境来验证什么是正常的crane体验，再把集群添加到dashboard后会自动生成一堆资源推荐的结果。https://gocrane.io/docs/getting-started/quick-start/
然后，如果你的环境里的资源推荐是异常的，那么很可能是由于访问prom失败导致craned整体功能的异常。

**Comment by qmhu** [comment]
@xinsir88 可以参考下最新的文档部分，有不清楚的再讨论：https://gocrane.io/zh-cn/docs/getting-started/installation/#%E4%BD%BF%E7%94%A8%E5%A4%96%E9%83%A8%E7%9A%84-prometheus%E5%8F%AF%E9%80%89
