### ISSUE TITLE
推荐报错

### ISSUE THREAD

**Issue by tripitakav** [gocrane/crane#608]
**Describe the bug**
![image](https://user-images.githubusercontent.com/73687556/201076743-a07ca6c8-4e9e-405e-abe9-f2b8d2ab8c70.png)

**Reproduce steps**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: [1.20]
 - Crane Version: [0.8.0]

**Comment by qmhu** [comment]
Is your craned crashed some times?
Please provide the result for command: `kubectl get crds`

**Comment by tripitakav** [comment]
It has been repaired. It is really missing some crds. Thank you
