### ISSUE TITLE
can oom-record show the pod's namespace

### ISSUE THREAD

**Issue by zj452008181** [gocrane/crane#610]
in my cluster ,there are many service deploy to diffrent namespaces,oom-record do not show namespace,it's hard to  find out oom service。

**Comment by qmhu** [comment]
I think it is a suitable requirment,

**Comment by qmhu** [comment]
@zj452008181 resolved

**Comment by zj452008181** [comment]
![9590568f-fd4c-4359-abb7-54901ba43e2a](https://user-images.githubusercontent.com/26154743/203246292-0af32b98-9901-4f26-914d-46810b1bc45f.png)
