### ISSUE TITLE
crane agent panic 

### ISSUE THREAD

**Issue by EchoUtopia** [gocrane/crane#614]
**Describe the bug**
following this tutorial: https://gocrane.io/zh-cn/docs/tutorials/colocation-with-enhanced-qos/qos-interference-detection-and-active-avoidance.zh/
after applying disablescheduling avoidanceaction and nodeqos,  the expecting taints are not set on the node which trigger the threshold.

checking crane-agent logs, it panics:
![image](https://user-images.githubusercontent.com/6038336/202427922-46776b16-f7ec-4186-91f4-9f51b6d618d1.png)

and the node's event are :
Warning AvoidanceTriggered crane-agent waterline1/cpu-usage triggered action disablescheduling/
**Reproduce steps**
described as description above

**Expected behavior**
the node be set taints when trigger the cpu usage threshold

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: 1.18.6, gitcommit: dc7354, goversion: 1.13.9, platform: linux/amd64
 - Crane Version: v0.8.0
 - Client: Docker Engine - Community
Version:           20.10.7
API version:       1.41
Go version:        go1.13.15
Git commit:        f0df350
OS/Arch:           linux/amd64
Context:           default
Experimental:      true

Server: Docker Engine - Community
Engine:
Version:          20.10.7
API version:      1.41 (minimum version 1.12)
Go version:       go1.13.15
Git commit:       b0f5bc3
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          1.4.8
GitCommit:        7eba5930496d9bbe375fdf71603e610ad737d2b2
runc:
Version:          1.0.0
GitCommit:        v1.0.0-0-g84113ee
docker-init:
Version:          0.19.0
GitCommit:        de40ad0

**Comment by chenkaiyue** [comment]
We will fix it in 0.9.0. Thx for your issue.

**Comment by EchoUtopia** [comment]
after update image to 0.9.0, the panic still happens
![607e861429c7f966b107fba278ab2d7](https://user-images.githubusercontent.com/6038336/219597468-f37d453e-caed-44a5-966e-d9352721fc98.jpg)

**Comment by chenkaiyue** [comment]
Thx, we will fix soon.
