### ISSUE TITLE
inconsistent crd name between examples dir and deploy dir

### ISSUE THREAD

**Issue by EchoUtopia** [gocrane/crane#615]
**Describe the bug**
in latest code in main branch, the crd of NodeQOS in deployment dir turned NodeQOSEnsurancePolicy in deploy dir

**Reproduce steps**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]

**Comment by chenkaiyue** [comment]
Thx, we will fix it.
