### ISSUE TITLE
镜像下载过慢问题

### ISSUE THREAD

**Issue by wangcong010** [gocrane/crane#616]
**Describe the bug**
使用docker pull镜像速度太慢，一分钟不到100K，还经常失败，已尝试各种镜像加速源，不好使。
是否考虑通过将 docker save 后的文件上传到git hub或其他地方，使得用户可以方便下载使用？

**Reproduce steps**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]

**Comment by qmhu** [comment]
You can try this:

```
docker pull finops-docker.pkg.coding.net/gocrane/crane/craned:v0.8.0
```

https://finops.coding.net/public-artifacts/gocrane/crane/craned/version/18371335/guide
