### ISSUE TITLE
安装完后crane界面无数据显示

### ISSUE THREAD

**Issue by liu843564014** [gocrane/crane#630]
agent相关报错日志如下：
E1129 09:11:46.093602       1 node_resource_manager.go:276] Failed to get tsp: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"timeseriesprediction.prediction.crane.io \"\" not found", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc006243f80), Code:404}}
E1129 09:11:56.051393       1 node_resource_manager.go:276] Failed to get tsp: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"timeseriesprediction.prediction.crane.io \"\" not found", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc007dec6c0), Code:404}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x18c805a]
goroutine 4264 [running]:
github.com/gocrane/crane/pkg/ensurance/collector/cadvisor.(*CadvisorCollector).Collect(0xc000c7acf0)
	/go/src/github.com/gocrane/crane/pkg/ensurance/collector/cadvisor/cadvisor_linux.go:167 +0x139a
github.com/gocrane/crane/pkg/ensurance/collector.(*StateCollector).Collect.func1.1({0x7f8c23f54f38, 0xc000c7acf0}, 0xc002213f50)
	/go/src/github.com/gocrane/crane/pkg/ensurance/collector/collector.go:154 +0x1a3
created by github.com/gocrane/crane/pkg/ensurance/collector.(*StateCollector).Collect.func1
	/go/src/github.com/gocrane/crane/pkg/ensurance/collector/collector.go:150 +0x1fd

另：是否有crane团队相关微信或微信群可以直接交流。感谢

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.17.5]
 - Crane Version: [e.g. 0.8.0]
 - Browser [edge]

**Comment by qmhu** [comment]
Looks like you should install crds when upgrade crane to newest version.

![image](https://user-images.githubusercontent.com/6251116/204701577-607db8a3-00ba-400b-ac71-a9ac834c62e3.png)

**Comment by qmhu** [comment]
@liu843564014 Is your problem resolved?

**Comment by liu843564014** [comment]
Yes, thank you, and wefind a new problem for

**Comment by liu843564014** [comment]
> @liu843564014 Is your problem resolved?
感谢，成本分布界面显示问题已找到解决方法。

但我们又发现实例推荐有异常的实例数，如下图：实例数达到了15291734个。现实中是不可能达成的，因为每个节点默认只有110个pod配额。
![image](https://user-images.githubusercontent.com/110508188/206352057-672876e6-a48f-4b5b-9c20-6e07fcd0a1a8.png)

**Comment by bumblebeeK** [comment]
> Looks like you should install crds when upgrade crane to newest version.
> 
> ![image](https://user-images.githubusercontent.com/6251116/204701577-607db8a3-00ba-400b-ac71-a9ac834c62e3.png)
Could u send this QR code again？ 
This invite link has expired,thinks.

**Comment by qmhu** [comment]
> > Looks like you should install crds when upgrade crane to newest version.
> > ![image](https://user-images.githubusercontent.com/6251116/204701577-607db8a3-00ba-400b-ac71-a9ac834c62e3.png)
> > Could u send this QR code again？
> > This invite link has expired,thinks.

![image](https://user-images.githubusercontent.com/6251116/214524460-39df42c5-cd6e-4899-9707-bab0649bf3ec.png)
