### ISSUE TITLE
有计划加入hook机制么

### ISSUE THREAD

**Issue by sunnoy** [gocrane/crane#638]
## Describe the feature

# 场景
当集群内资源扩缩容的时候，需要和集群外的资源进行联动和编排，达到整体环境资源节省以及整个环境可用性的保证

**Comment by qmhu** [comment]
首先确认下修改资源是指修改什么对象的资源，是pod还是node？

**Comment by sunnoy** [comment]
pod 比如副本数 或在资源配置 这个时候可能会触发集群外的资源缩减 比如中间件之类的

**Comment by qmhu** [comment]
> pod 比如副本数 或在资源配置 这个时候可能会触发集群外的资源缩减 比如中间件之类的

这种webhook一旦部署，就有可能影响用户的关键链路，影响到用户的业务，所以我们对此比较谨慎。这种功能可以通过controller实现会好一些。

还有一种方案是基于推荐框架实现，可以基于recommendation的crd结果生成优化编排任务，由用户来控制什么情况执行。

**Comment by sunnoy** [comment]
这个思路可以 谢谢
