### ISSUE TITLE
docs: Support a user-guide docs for kubectl-crane  CLI tool

### ISSUE THREAD

**Issue by mangoGoForward** [gocrane/crane#654]
## Describe the feature
We have implemented CLI tool for `crane` in gocrane/kubectl-crane#8 and gocrane/kubectl-crane#9, it supported a way to create a recommendation rule simply, adopt a recommend result  or view which related recommend results for a deployment and so on.

And we'd like to add a user-guide docs for this CLI tool, it should contain:

- How to install `kubectl-crane`? 
- How to use `kubectl-crane`? 
  We described some examples for each sub-command like https://github.com/gocrane/kubectl-crane/blob/fefd850def70a756f44d773fc932b1cf006a3f84/pkg/cmd/recommendationRule/create.go#L22-L32

cc @qmhu

**Comment by qmhu** [comment]
Looking forward for this plugin!
