### ISSUE TITLE
”集群总览“无数据显示BUG

### ISSUE THREAD

**Issue by liu843564014** [gocrane/crane#665]
**问题：”集群总览“无数据显示**
![image](https://user-images.githubusercontent.com/110508188/209519934-af297467-3e5a-4e06-ae27-91c2f90acf96.png)
crane日志显示 **craned容器 --->dashboard端口**tcp超时
![image](https://user-images.githubusercontent.com/110508188/209520090-3fb86425-17ea-419f-8e7c-ac912d1a812d.png)
dashboard的ingress超时时间已放大到600s，仍然无法正常加载数据
![image](https://user-images.githubusercontent.com/110508188/209520402-ee37c37d-494e-47bf-9210-8a31c1c55f4f.png)

crane&dashboard版本：v0.9.0

**Comment by liu843564014** [comment]
补充：
**1：在普罗用以下命令是可以得到value结果的。**
sum (
      avg(
          sum_over_time(node:node_total_hourly_cost:avg[30d])
          * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~"eklet", label_node_kubernetes_io_instance_type!~"eklet"}) by (node)
      )
![755e4ed48e0e8a481d5063a17a46ba5](https://user-images.githubusercontent.com/110508188/210288625-c8872a43-ada1-4687-bf7b-3b6fcb08d893.png)

  by (node))
**2：craned主页，前端所有502的连接已自动重试直到200才结束。但“集群总览“仍然是无数据显示，只能识别到namespaces分类。**
![44d4ef3074db22fc37447480e0824b0](https://user-images.githubusercontent.com/110508188/210288632-65a17812-1e84-41b8-9777-0c9c15d9d6d4.png)

**Comment by qmhu** [comment]
We might support an options to config timeout for prometheus query. In some usecase, the default timeout is too short.

**Comment by qmhu** [comment]
I think your problem is the same to https://github.com/gocrane/crane/issues/674. You can set discount and retry. 
 @liu843564014
