### ISSUE TITLE
基于helm安装scheduler报错404

### ISSUE THREAD

**Issue by kubehan** [gocrane/crane#669]
## Describe the feature
![image](https://user-images.githubusercontent.com/69997301/209926563-05d11f40-7b30-4a1f-8400-b329edb80111.png)

[root@VM-16-8-centos ~]# helm install scheduler -n crane-system --create-namespace crane/scheduler
Error: INSTALLATION FAILED: failed to fetch https://github.com/gocrane/helm-charts/releases/download/scheduler-0.2.1/scheduler-0.2.1.tgz : 404 Not Found

**Comment by qmhu** [comment]
Fixed.
