### ISSUE TITLE
recommendation metrics lost after restart craned

### ISSUE THREAD

**Issue by zxh326** [gocrane/crane#672]
**Describe the bug**

```
crane_analysis_resource_recommendation
crane_analysis_resource_recommendation
...
```

**Reproduce steps**
1. start craend
2. recommend success once
3. confirm metrics exists
3. restart craned
4. metrics lost

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: 1.22
 - Crane Version: 0.9.0

**Comment by qmhu** [comment]
The metric is produced when process recommendation. so if craned restarted it will lost until new recommendation come.

**Comment by zxh326** [comment]
> The metric is produced when process recommendation. so if craned restarted it will lost until new recommendation come.

The metrics data should be in `Recommendation` crds? Can we reload it when start it?

**Comment by qmhu** [comment]
> > The metric is produced when process recommendation. so if craned restarted it will lost until new recommendation come.
> 
> The metrics data should be in `Recommendation` crds? Can we reload it when start it?

em... It's better to record metric in Recommendation controller. That can resolve this problem.

**Comment by qmhu** [comment]
> > The metric is produced when process recommendation. so if craned restarted it will lost until new recommendation come.
> 
> The metrics data should be in `Recommendation` crds? Can we reload it when start it?



> > > The metric is produced when process recommendation. so if craned restarted it will lost until new recommendation come.
> > 
> > 
> > The metrics data should be in `Recommendation` crds? Can we reload it when start it?
> 
> em... It's better to record metric in Recommendation controller. That can resolve this problem.

@zxh326 are you willing to refactor it ?

**Comment by zxh326** [comment]
@qmhu  Sure..I will try to refactor it in my free time.

/assign

**Comment by qmhu** [comment]
Hi @zxh326 , is there any progress for it? Other user have the same requirement.

**Comment by whitebear009** [comment]
@qmhu   meet the same issue. I have created [PR](https://github.com/gocrane/crane/pull/693) for this.

**Comment by zxh326** [comment]
> @qmhu meet the same issue. I have created [PR](https://github.com/gocrane/crane/pull/693) for this.

👍



> Hi @zxh326 , is there any progress for it? Other user have the same requirement.

sry

/assign @whitebear009
