### ISSUE TITLE
Inconsistent recommender annotation has been set in Recommendations

### ISSUE THREAD

**Issue by GoneLikeAir** [gocrane/crane#679]
**Describe the bug**
In a Resource Recommendation, the "analysis.crane.io/recommendation-rule-recommender" has been set to "Replicas". And the annotation of a Replica Recommdation has been set to "resource".

**Reproduce steps**

**Expected behavior**
In ReplicasRecommendation, set the recommender annotation to "Replicas". "Resource" set to ResourceRecommendation as the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/49898234/212630498-c7aa7037-c6b9-4867-8cba-6f5f0fd7d60b.png)

![image](https://user-images.githubusercontent.com/49898234/212630925-e586bf1b-2651-4c50-ab46-f31c85caab30.png)

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 1.16.3
 - Crane Version: [e.g. 0.1.0]
0.7.0

**Comment by qmhu** [comment]
I can reproduce in my env... Would you like to upgrade to newest version and delete all recommendation and see whether it happens.
```
kubectl delete recommend --all -A
```
