### ISSUE TITLE
Optimization: rbac clusterrole for crane is too open

### ISSUE THREAD

**Issue by fm2022aa** [gocrane/crane#688]
**Describe the bug**
https://github.com/gocrane/crane/blob/7b43222f8f1a73a9f32faa5ca472c632067ddbb2/deploy/craned/rbac.yaml
```apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: craned
rules:
  - apiGroups: [ '*' ]
    resources: [ '*' ]
    verbs: [ "*" ]
```

**Reproduce steps**
**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

**Comment by qmhu** [comment]
Would you like to enhance it?

**Comment by lbbniu** [comment]
assign me?
