### ISSUE TITLE
sum(crane_analysis_resource_recommendation{resource="cpu"}) 推荐总量会不断上涨， why？

### ISSUE THREAD

**Issue by justzx2011** [gocrane/crane#695]
**Describe the bug**
crane_analysis_resource_recommendation{apiversion="extensions/v1beta1",container="app",namespace="ns1",owner_kind="Deployment",owner_name="x-online-tmp-3-f3913-7hcal",owner_replicas="10",resource="cpu"} 0.2
crane_analysis_resource_recommendation{apiversion="extensions/v1beta1",container="app",namespace="ns1",owner_kind="Deployment",owner_name="x-online-tmp-3-f3913-7hcal",owner_replicas="10",resource="memory"} 3.44532114e+08
crane_analysis_resource_recommendation{apiversion="extensions/v1beta1",container="app",namespace="ns1",owner_kind="Deployment",owner_name="x-online-tmp-3-f3913-7hcal",owner_replicas="3",resource="cpu"} 0.2
crane_analysis_resource_recommendation{apiversion="extensions/v1beta1",container="app",namespace="ns1",owner_kind="Deployment",owner_name="x-online-tmp-3-f3913-7hcal",owner_replicas="3",resource="memory"} 3.44532114e+08

同一个负载：owner_name="x-online-tmp-3-f3913-7hcal"，做了缩容之后，owner_replicas从10降到了3，但是指标数据会都记录下来，导致推荐总量（cpu、memory）会不断上涨。

**Reproduce steps**
创建测试rr，每分钟运行一次，测试负载先创建10个pod，过2分钟缩减到3个，查看/metrics数据，发现缩容前后推荐数据都会展示

**Expected behavior**
仅展示最新一次推荐数据，也就是：
crane_analysis_resource_recommendation{apiversion="extensions/v1beta1",container="app",namespace="ns1",owner_kind="Deployment",owner_name="x-online-tmp-3-f3913-7hcal",owner_replicas="3",resource="cpu"} 0.2
crane_analysis_resource_recommendation{apiversion="extensions/v1beta1",container="app",namespace="ns1",owner_kind="Deployment",owner_name="x-online-tmp-3-f3913-7hcal",owner_replicas="3",resource="memory"} 3.44532114e+08
**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: 1.13.12
 - Crane Version: v0.9.0
 - Browser: chrome

**Comment by qmhu** [comment]
fixed.
