### ISSUE TITLE
Can we make the resources recommender histogram adjustable

### ISSUE THREAD

**Issue by zxh326** [gocrane/crane#698]
## Describe the feature

Is it possible to make the current configuration adjustable instead of being fixed, as it results in the recommended resources, for example in the case of CPU, being at a minimum of "0.1 core"?

https://github.com/gocrane/crane/blob/c330f133a628d782b14a90fc9e93dc6c8e14db74/pkg/recommendation/recommender/resource/recommend.go#L59-L63

**Comment by qmhu** [comment]
This configuration can be exported with recommendation configuration.  Anyone who want to contribute it could take it.

**Comment by qixiang-liu** [comment]
Enjoy it !!!!!

**Comment by qmhu** [comment]
Thank you for contribution!
