### ISSUE TITLE
CPU 内存的总容量获取能自己定义吗？

### ISSUE THREAD

**Issue by llussy** [gocrane/crane#702]
我的集群有虚拟节点，capacity 比较大，影响分析，想去掉虚拟节点。
```bash
Capacity:
  cpu:                192k
  ephemeral-storage:  600000Gi
  hugepages-2Mi:      60Ti
  memory:             640Ti
  nvidia.com/gpu:     10k
  pods:               30k
Allocatable:
  cpu:                192k
  ephemeral-storage:  600000Gi
  hugepages-2Mi:      60Ti
  memory:             640Ti
  nvidia.com/gpu:     10k
  pods:               30k
```
![image](https://user-images.githubusercontent.com/18432966/220633503-a7de0cee-2ece-4402-945a-9ac09be3e92e.png)

**Comment by qmhu** [comment]
现在统计时去除了腾讯的serverless节点，label是：label_beta_kubernetes_io_instance_type!=\"eklet\"，你可以参考你的label修改。不过首页的展示只能通过修改前端代码的方式实现，grafana页面可以直接admin登陆修改配置实现。

后续首页的图表我们也会加入到grafana，方便用户修改promql配置。

**Comment by llussy** [comment]
> 现在统计时去除了腾讯的serverless节点，label是：label_beta_kubernetes_io_instance_type!="eklet"，你可以参考你的label修改。不过首页的展示只能通过修改前端代码的方式实现，grafana页面可以直接admin登陆修改配置实现。
> 
> 后续首页的图表我们也会加入到grafana，方便用户修改promql配置。

感谢解答，我把虚拟节点增加了label `label_beta_kubernetes_io_instance_type!="eklet"`,现在可以正常显示了。

**Comment by qmhu** [comment]
> 

这也是一个workround办法 👍

**Comment by llussy** [comment]
**补充下**
具体增加label的命令
```bash
kubectl label node virtual-kubelet-cn-beijing-j beta_kubernetes_io_instance_type=eklet
```
我这的 `kube-state-metrics` 默认不会采集node labels信息，kube-state-metrics需要增加一个参数 `- --metric-labels-allowlist=nodes=[*]`
