### ISSUE TITLE
container_cpu_usage_costs_hourly 等指标不存在

### ISSUE THREAD

**Issue by llussy** [gocrane/crane#710]
`container_cpu_usage_costs_hourly`  `container_memory_usage_costs_hourly` 等指标不存在，是我缺少了什么吗？
![image](https://user-images.githubusercontent.com/18432966/223041507-627fe5eb-e2f2-44a6-ba47-3b8012d6aad9.png)

`crane-daemonset` `craned` `fadvisor` 的 servicemonitor 已部署

![image](https://user-images.githubusercontent.com/18432966/223041585-5c832b61-7e67-4551-a9dc-09e1dce79684.png)

**Comment by qmhu** [comment]
You should wait a while for xxx_costs_hourly metrics.

**Comment by llussy** [comment]
> You should wait a while for xxx_costs_hourly metrics.

It's been seven hours since restarting, I'll check it out tomorrow.

**Comment by qmhu** [comment]
The metrics are from here:https://github.com/gocrane/helm-charts/blob/main/integration/prometheus/override_values.yaml#L13

If not exist, please also checking the recording rules in prometheus.

**Comment by llussy** [comment]
> 

Thanks, I am using the existing promethues, which is missing this part, and it is fine now.
