### ISSUE TITLE
使用页面上提供的资源推荐采纳命令报错

### ISSUE THREAD

**Issue by yangjiajun2014** [gocrane/crane#715]
**Describe the bug**
运行采纳命令，报以下错：
The Deployment "xxx" is invalid: spec.template.spec.containers[0].image: Required value

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.9.0]

**Comment by qmhu** [comment]
Please provide the yaml for recommendation.

**Comment by yangjiajun2014** [comment]
> Please provide the yaml for recommendation.

Thanks for u reply.Here is the yaml:
`apiVersion: analysis.crane.io/v1alpha1
kind: Recommendation
metadata:
  creationTimestamp: "2023-01-18T07:15:42Z"
  generateName: workloads-rule-resource-
  generation: 114
  labels:
    analysis.crane.io/recommendation-rule-name: workloads-rule
    analysis.crane.io/recommendation-rule-recommender: Resource
    analysis.crane.io/recommendation-rule-uid: 06fa57f8-1eb5-4161-8328-4d302addad21
    analysis.crane.io/recommendation-target-kind: Deployment
    analysis.crane.io/recommendation-target-name: deployment-xxx
    analysis.crane.io/recommendation-target-version: v1
    app: xxxxxx
    part-of: xxx
    tier: api
    version: 1.0.0
  managedFields:
  - apiVersion: analysis.crane.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:analysis.crane.io/recommendation-rule-name: {}
          f:analysis.crane.io/recommendation-rule-recommender: {}
          f:analysis.crane.io/recommendation-rule-uid: {}
          f:analysis.crane.io/recommendation-target-kind: {}
          f:analysis.crane.io/recommendation-target-name: {}
          f:analysis.crane.io/recommendation-target-version: {}
          f:app: {}
          f:part-of: {}
          f:tier: {}
          f:version: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"06fa57f8-1eb5-4161-8328-4d302addad21"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        .: {}
        f:adoptionType: {}
        f:completionStrategy:
          .: {}
          f:completionStrategyType: {}
        f:targetRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
        f:type: {}
      f:status:
        .: {}
        f:action: {}
        f:conditions: {}
        f:currentInfo: {}
        f:lastUpdateTime: {}
        f:recommendedInfo: {}
        f:recommendedValue: {}
        f:targetRef: {}
    manager: craned
    operation: Update
    time: "2023-01-18T07:15:42Z"
  name: workloads-rule-resource-24n5b
  namespace: api
  ownerReferences:
  - apiVersion: analysis.crane.io/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: RecommendationRule
    name: workloads-rule
    uid: 06fa57f8-1eb5-4161-8328-4d302addad21
  resourceVersion: "420903663"
  selfLink: /apis/analysis.crane.io/v1alpha1/namespaces/api/recommendations/workloads-rule-resource-24n5b
  uid: b595f372-cfbb-4e74-b592-044cb8bf96bc
spec:
  adoptionType: StatusAndAnnotation
  completionStrategy:
    completionStrategyType: Once
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-xxx
    namespace: api
  type: Resource
status:
  action: Patch
  conditions:
  - lastTransitionTime: "2023-03-08T15:30:29Z"
    message: Recommendation is ready
    reason: RecommendationReady
    status: "True"
    type: Ready
  currentInfo: '{"spec":{"template":{"spec":{"containers":[{"name":"container-xxxxxx","resources":{"requests":{"cpu":"2","memory":"4Gi"}}}]}}}}'
  lastUpdateTime: "2023-03-12T16:05:51Z"
  recommendedInfo: '{"spec":{"template":{"spec":{"containers":[{"name":"container-xxxxxx","resources":{"requests":{"cpu":"1","memory":"2Gi"}}}]}}}}'
  recommendedValue: |
    resourceRequest:
      containers:
      - containerName: container-xxxxxx
        target:
          cpu: "1"
          memory: 2Gi
  targetRef: {}`

**Comment by yangjiajun2014** [comment]
Sorry.Crane wokrs fine.It's my fault.
