### ISSUE TITLE
Idle Node Plugin Enhancement

### ISSUE THREAD

**Issue by qmhu** [gocrane/crane#737]
## Describe the feature

Find idle node with following rules:
- cpu/memory request rate
- cpu/memory utilization rate

It need to implement some configuration for this plugin:

- cpu-request-utilization
- cpu-usage-utilization
- memory-request-utilization
- memory-usage-utilization

**Comment by xiu111** [comment]
To implement the feature of finding idle nodes in the Crane open-source project based on CPU and memory request/utilization rates, you can follow these steps:

1. Clone the Crane repository: Start by cloning the Crane repository from GitHub using the following command:
   ```
   git clone https://github.com/gocrane/crane.git
   ```

2. Navigate to the plugin directory: Change your working directory to the `plugins` folder within the Crane project.

3. Create a new Go file: Create a new Go file, such as `idle_nodes.go`, in the `plugins` directory.

4. Implement the idle nodes plugin: In the `idle_nodes.go` file, you'll need to implement the logic to find idle nodes based on the provided rules. Here's a basic example to get you started:

   ```go
   package main

   import (
   	"fmt"
   	"log"

   	"github.com/gocrane/crane/api"
   	"github.com/gocrane/crane/executor"
   )

   func main() {
   	// Initialize Crane executor
   	executor := executor.NewDefaultExecutor()

   	// Get all nodes
   	nodes, err := executor.GetNodes()
   	if err != nil {
   		log.Fatal("Failed to get nodes:", err)
   	}

   	// Iterate over each node and check utilization
   	for _, node := range nodes {
   		cpuRequestUtilization := node.CPURequestUtilization()
   		cpuUsageUtilization := node.CPUUsageUtilization()
   		memoryRequestUtilization := node.MemoryRequestUtilization()
   		memoryUsageUtilization := node.MemoryUsageUtilization()

   		// Check if the node meets the configuration criteria
   		if cpuRequestUtilization < cpuRequestUtilizationThreshold &&
   			cpuUsageUtilization < cpuUsageUtilizationThreshold &&
   			memoryRequestUtilization < memoryRequestUtilizationThreshold &&
   			memoryUsageUtilization < memoryUsageUtilizationThreshold {
   			fmt.Println("Idle node:", node.Name)
   		}
   	}
   }
   ```

   In this example, we're using the Crane executor to retrieve all nodes and check their CPU and memory request/utilization rates against the provided thresholds. If a node meets the criteria, it's considered an idle node.

5. Configure the plugin: Define the configuration values for the CPU and memory request/utilization thresholds (cpu-request-utilization, cpu-usage-utilization, memory-request-utilization, memory-usage-utilization) based on your specific requirements. These thresholds will be used to determine if a node is idle.

6. Build and run the plugin: Build the Crane project with your custom plugin using the following command:
   ```
   go build -o crane .
   ```

7. Run the plugin: Execute the Crane binary to run the plugin and find the idle nodes in your cluster:
   ```
   ./crane plugin idle_nodes
   ```

   The output will display the names of any idle nodes that meet the specified CPU and memory request/utilization rate criteria.

By following these steps, you can extend the Crane open-source project with a custom plugin to find idle nodes in your Kubernetes cluster based on CPU and memory request/utilization rates. Adjust the configuration and thresholds as per your specific needs.

**Comment by qmhu** [comment]
> To implement the feature of finding idle nodes in the Crane open-source project based on CPU and memory request/utilization rates, you can follow these steps:
> 
> 1. Clone the Crane repository: Start by cloning the Crane repository from GitHub using the following command:
>    ```
>    git clone https://github.com/gocrane/crane.git
>    ```
> 2. Navigate to the plugin directory: Change your working directory to the `plugins` folder within the Crane project.
> 3. Create a new Go file: Create a new Go file, such as `idle_nodes.go`, in the `plugins` directory.
> 4. Implement the idle nodes plugin: In the `idle_nodes.go` file, you'll need to implement the logic to find idle nodes based on the provided rules. Here's a basic example to get you started:
>    ```go
>    package main
>    
>    import (
>    	"fmt"
>    	"log"
>    
>    	"github.com/gocrane/crane/api"
>    	"github.com/gocrane/crane/executor"
>    )
>    
>    func main() {
>    	// Initialize Crane executor
>    	executor := executor.NewDefaultExecutor()
>    
>    	// Get all nodes
>    	nodes, err := executor.GetNodes()
>    	if err != nil {
>    		log.Fatal("Failed to get nodes:", err)
>    	}
>    
>    	// Iterate over each node and check utilization
>    	for _, node := range nodes {
>    		cpuRequestUtilization := node.CPURequestUtilization()
>    		cpuUsageUtilization := node.CPUUsageUtilization()
>    		memoryRequestUtilization := node.MemoryRequestUtilization()
>    		memoryUsageUtilization := node.MemoryUsageUtilization()
>    
>    		// Check if the node meets the configuration criteria
>    		if cpuRequestUtilization < cpuRequestUtilizationThreshold &&
>    			cpuUsageUtilization < cpuUsageUtilizationThreshold &&
>    			memoryRequestUtilization < memoryRequestUtilizationThreshold &&
>    			memoryUsageUtilization < memoryUsageUtilizationThreshold {
>    			fmt.Println("Idle node:", node.Name)
>    		}
>    	}
>    }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    In this example, we're using the Crane executor to retrieve all nodes and check their CPU and memory request/utilization rates against the provided thresholds. If a node meets the criteria, it's considered an idle node.
> 5. Configure the plugin: Define the configuration values for the CPU and memory request/utilization thresholds (cpu-request-utilization, cpu-usage-utilization, memory-request-utilization, memory-usage-utilization) based on your specific requirements. These thresholds will be used to determine if a node is idle.
> 6. Build and run the plugin: Build the Crane project with your custom plugin using the following command:
>    ```
>    go build -o crane .
>    ```
> 7. Run the plugin: Execute the Crane binary to run the plugin and find the idle nodes in your cluster:
>    ```
>    ./crane plugin idle_nodes
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    The output will display the names of any idle nodes that meet the specified CPU and memory request/utilization rate criteria.
> 
> By following these steps, you can extend the Crane open-source project with a custom plugin to find idle nodes in your Kubernetes cluster based on CPU and memory request/utilization rates. Adjust the configuration and thresholds as per your specific needs.

Is this generate from gpt?
