### ISSUE TITLE
优化前端代码，使其通过eslint 验证

### ISSUE THREAD

**Issue by PmcFizz** [gocrane/crane#742]
**Describe the bug**
前端代码引入了eslint，用来校验代码，但目前没有用起来，依然存在很多警告和错误。

**Reproduce steps**
进入pkg/web目录，执行npm run lint
会检验出很多的 警告和错误。

**Expected behavior**
修复所有错误，选择性修复警告。

**Screenshots**
![image](https://user-images.githubusercontent.com/13403284/234530912-888f9f90-2558-4bb8-976a-9afbfe45bbdd.png)

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]

**Comment by JaneConan** [comment]
[[bootcamp](https://github.com/gocrane/crane/labels/bootcamp)] I would like to work on it~

**Comment by JaneConan** [comment]
请教一下，只修复error就可以了么
![image](https://user-images.githubusercontent.com/26090153/236139400-e21ef023-39bf-4f0a-93ec-e846c4805e44.png)

warning 中 有一些特殊符号，想请教一下这些代表什么意思

**Comment by JaneConan** [comment]
我执行了如下语句
``` bash
npm run lint -- --fix
```

错误修复了大部分，然后还有88个，这些是需要手动调整的吧
![image](https://user-images.githubusercontent.com/26090153/236142262-aa0ee3a5-c84c-45f5-bdf7-072c589f6e40.png)

**Comment by PmcFizz** [comment]
> 我执行了如下语句
> 
> ```shell
> npm run lint -- --fix
> ```
> 
> 错误修复了大部分，然后还有88个，这些是需要手动调整的吧 ![image](https://user-images.githubusercontent.com/26090153/236142262-aa0ee3a5-c84c-45f5-bdf7-072c589f6e40.png)

由于涉及文件非常多，且改动比较大。建议与官方开发人员协商，分批，修复，提交 review。

**Comment by JaneConan** [comment]
@PmcFizz 好的，感谢您的指导

胡老师 @qmhu  这边我之前有联系，目前我想知道crane的前端团队负责人，再帮忙看看

目前手改了一些，并提交了pr，剩下这些需要和大家再讨论了

![image](https://user-images.githubusercontent.com/26090153/236160075-a3ad2e88-bb3e-4566-9b06-fe57d2913ec4.png)

**Comment by qmhu** [comment]
bootcamp的issue和代码提交希望能够完成一些功能方面的能力，前端主要是做一个展示和demo为主，基本功能可用即可
