### ISSUE TITLE
Typo in comments - There is a typo in the comments of the cost.go file

### ISSUE THREAD

**Issue by xiu111** [gocrane/crane#743]
**Describe the bug**
  错别字
**Reproduce steps**
Typo in comments - There is a typo in the comments of the cost.go file, where "ambigious" is spelled incorrectly as "amibiguous". This should be corrected to maintain consistency and clarity in the codebase.
其中“ambigious”拼写错误为“amibiguous”。这一点应该加以纠正，以保持代码库的一致性和清晰度。

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]

**Comment by qmhu** [comment]
Thanks
