### ISSUE TITLE
web 项目优化问题

### ISSUE THREAD

**Issue by RuoChengF** [gocrane/crane#752]
细节如下图所示:  **Workload类型** 与后面的 **Workload** 都是下拉选择 建议将两个合在一起 , 同时在下拉选项中默认添加一个全选选项,或者默认就是全选 
 

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/73278512/236143697-3ef0d014-50c3-4d52-bb30-970255f5fed0.png">

**Comment by qmhu** [comment]
Not a suitable advise.
