### ISSUE TITLE
集群管理弹出框一次点击不能生效且错误闪烁问题

### ISSUE THREAD

**Issue by qingtiantongxie** [gocrane/crane#758]
**Describe the bug**
集群管理页面，添加集群在某些固定操作下会闪烁并不能正常弹出

**Reproduce steps**
1. 先访问 http://dashboard.gocrane.io/#/settings/cluster
2. 点击`添加集群`并成功添加一个集群
3. 点击列表中的`修改`
4. 在弹出框中选择`取消`关闭弹出框
5. 点击`添加集群`按钮即可看到问题

由于闪烁很快，不能截取画面，复现请按照步骤操作

![image](https://user-images.githubusercontent.com/24731632/236181957-e1ed75e9-6783-4965-ace5-62c7d0059589.png)

**Expected behavior**
弹出框功能正常使用

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]

**Comment by lbbniu** [comment]
是不是你鼠标点击了空白区域

**Comment by qingtiantongxie** [comment]
不是哦  按照截图操作步骤  没有点击空白区域
