### ISSUE TITLE
镜像安装时不支持X86架构CPU

### ISSUE THREAD

**Issue by donsmile** [gocrane/crane#764]
## Describe the feature
环境：model name	: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz  CentOS Linux release 7.9.2009 (Core)环境下，安装出现问题。
pod logs报错：standard_init_linux.go:228: exec user process caused: exec format error
pod状态 describe logs截图如下：
![微信图片_20230507130910](https://user-images.githubusercontent.com/27986841/236658957-14d72372-cf5e-486e-bb57-bb3ca5adb40a.png)
![微信图片_20230507130738](https://user-images.githubusercontent.com/27986841/236658966-030c501b-d4cf-48f0-91f8-78a16a450f9e.png)
![微信图片_20230507130759](https://user-images.githubusercontent.com/27986841/236658971-8301145a-c457-472b-9009-2629876c2ffb.png)

在做实验时发现，已在微信群与胡老师沟通此问题

**Comment by qmhu** [comment]
Fixed.
