### ISSUE TITLE
K8S集群外部访问，配置成nodeport仍无法访问

### ISSUE THREAD

**Issue by donsmile** [gocrane/crane#765]
环境：windows客户端无K8S服务，linux服务器部署K8S和Crane，默认是ClusterIP模式，通过官网的方式改成nodeport
![image](https://user-images.githubusercontent.com/27986841/236659162-fe26e388-3531-4467-9131-1661e68df705.png)
![image](https://user-images.githubusercontent.com/27986841/236659127-3b4b93e0-9a69-44fe-a850-399e8d04c527.png)
![image](https://user-images.githubusercontent.com/27986841/236659178-3ceb09b2-d849-4dc1-8147-3e831d819dc8.png)
这个地址仍是K8S内部访问地址，局域网的其他服务器无法使用：http://172.18.0.2:31839
但在K8S集群内部是可以访问的
![image](https://user-images.githubusercontent.com/27986841/236659223-e7c9b6b1-cd30-4f4c-b385-801719e7252b.png)
![image](https://user-images.githubusercontent.com/27986841/236659260-0df2dac5-6ca5-41de-8dda-22c678fc99ac.png)

**Comment by lbbniu** [comment]
服务都正常启动了吗？ 
```bash
kubectl -n crane-system get pod 
```

**Comment by donsmile** [comment]
> 服务都正常启动了吗？
> 
> ```shell
> kubectl -n crane-system get pod 
> ```

是的，后来我挂了一个NGINX反向代理就正常访问了，但是正常来说nodeport就可以直接访问。
