### ISSUE TITLE
前台时间范围不准确

### ISSUE THREAD

**Issue by liuqisha** [gocrane/crane#778]
**Describe the bug**
选择时间范围24小时，实际数据只有当天，不足24小时
**Reproduce steps**
成本洞察-应用总览-时间范围-24小时

**Expected behavior**
24小时时间范围是当前时间倒推24小时这个范围
**Screenshots**
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/30694892/236986109-0790dae0-dd49-4cac-951b-0aace0080d1c.png">
**Environment (please complete the following information):**
 - K8S Version: 1.21
 - Crane Version: 0.10.0
 - Browser: chrome

**Comment by zsnmwy** [comment]
It's a bug.
Thanks for your feedback.
We will fix it.

https://github.com/gocrane/crane/blob/912d800c6de07fb22804a04068921c967296f49c/pkg/web/src/utils/rangeMap.ts#L6
