### ISSUE TITLE
Request Crane Dashboard Service of Proxy Interface，Appear 502 Bad Gateway

### ISSUE THREAD

**Issue by ChenZhuang1217** [gocrane/crane#791]
**Describe the bug**

Request Crane Dashboard Service of Proxy Interface，Appear 502 Bad Gateway

**Reproduce steps**

curl Craned-Service-ClusterIP:9090/api/v1/cluster

![image](https://github.com/gocrane/crane/assets/86410747/98826816-03c1-4198-a7d3-6ed2bbeacb70)

**Expected  #behavior**

Modify Dashboard's ConfigMap to change all agent port 8082 requests in Nginx to 127.0.0.1 and communicate through the local Lo card.

Because in Kubernetes, the Pod cannot access itself directly through Service and port unless configured with  -hairpin-mode.

![image](https://github.com/gocrane/crane/assets/86410747/370dfa13-f56f-42c7-8c05-ca2be3f2a82c)

**Environment (please complete the following information):**
 - K8S Version: [1.18.3]
 - Crane Version: [0.9.0]
 - Browser [chrome]

**Comment by qmhu** [comment]
Why to change the configmap and expect it works?
And why we need to support it?

**Comment by ChenZhuang1217** [comment]
> 为什么要更改 configmap 并期望它有效？ 为什么我们需要支持它？

If no adjustment is made, 502 Bad Gateways are displayed when clusters are added to the Dashboard. Since the two containers are in the same Pod, you are advised to use the Lo local NIC for communication.

**Comment by ChenZhuang1217** [comment]
> Why to change the configmap and expect it works? And why we need to support it?

The cluster is always in the confirmation state
![image](https://github.com/gocrane/crane/assets/86410747/4abd2101-ac97-42f9-acf5-54d3679ee08a)

Dashboard Container Log Output Request Interface 502
![image](https://github.com/gocrane/crane/assets/86410747/b2784328-4ab9-4fcb-8f5f-93268bcb42a8)

**Comment by qmhu** [comment]
这里主要的考虑是通过DNS Domain访问服务，这样可以兼容各种环境的场景，如果你本地遇到访问不通的问题，可以自己修改配置解决。但是整体项目的配置会考虑更通用的场景。我不认为一个bug。
