### ISSUE TITLE
Installation of Grafana failed

### ISSUE THREAD

**Issue by Leynakindle** [gocrane/crane#831]
**Describe the bug**
I failed to install Grafana using the installation script provided in the official documentation, and it shows errors related to PodSecurityPolicy.

**Reproduce steps**
1. helm repo add grafana https://grafana.github.io/helm-charts
2. helm install grafana --version 6.11.0 \
    -f https://raw.githubusercontent.com/gocrane/helm-charts/main/integration/grafana/override_values.yaml \
    -n crane-system \
    --create-namespace grafana/grafana
<img width="964" alt="截屏2023-07-04 12 36 23" src="https://github.com/gocrane/crane/assets/3469381/51ab3b5b-80a3-4ee8-994e-37d2cac69362">

**Error log**
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "grafana" namespace: "crane-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "grafana-test" namespace: "crane-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first]
<img width="912" alt="截屏2023-07-04 12 34 43" src="https://github.com/gocrane/crane/assets/3469381/b2053c2d-8da6-4328-90f8-70f28656ec77">

**Environment (please complete the following information):**
 - K8S(RKE2) Version: v1.27.2+rke2r1
 - Helm Version: v3.12.1

**Comment by qmhu** [comment]
k8s version is too high for policy/v1beta1. you could try use larger version grafana for installation.

**Comment by Leynakindle** [comment]
> k8s version is too high for policy/v1beta1. you could try use larger version grafana for installation.

thanks, i have tried installing the latest version of Grafana, and the issue has been resolved.
