### ISSUE TITLE
社区持续不下去了么？

### ISSUE THREAD

**Issue by daxwang** [gocrane/crane#835]
## Describe the feature
社区会议最后一期是2023.3.15，后面就没有更新了，是不是已经死了啊，感觉已经持续不下去了，哎，可惜了

**Comment by clin4** [comment]
如果真这样是可惜了。

**Comment by mfanjie** [comment]
Crane项目依然是可持续发展的。
腾讯研发团队现在已经在用Crane纳管了腾讯内部自研业务的数百个集群，支撑了上千万核的业务规模，每年能为腾讯节省数亿成本，在精细化运营的过程中，也有很多能力迭代和一些问题修复，我们会在后续逐步把这些增强开源出来。

同时Crane在业界的影响力也在不断增强，除2022年获得国家级奖励以外，2023年又获得了”数博会领先科技成果优秀项目奖“。
https://cloud.tencent.com/developer/article/2295421?areaSource=&traceId=
