### ISSUE TITLE
Unit tests for crane

### ISSUE THREAD

**Issue by mfanjie** [gocrane/crane#91]
We need UT code for many functions, and many of them are isolated enough so they can be picked up by new comers.
For example match() in pkg/controller/analytics/analytics_controller.go, help needed.

**Comment by alierkilic** [comment]
Hey @mfanjie I can work on other tests as well. Please let me know.

**Comment by mfanjie** [comment]
@alierkilic I assigned this ticket to you, so everyone know you are working on it
